name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install build-essential pkg-config protobuf-compiler-grpc libgrpc-dev libgrpc++-dev
    - name: compile
      run: make
    - name: test
      run: make test
